// 자동 생성 파일 — scripts/build-icons.mjs 로 재생성
export type IconName =
  | "add"
  | "angle-small-down"
  | "angle-small-right"
  | "arrow-circle-up"
  | "checkbox"
  | "cross"
  | "drawer-empty"
  | "eye"
  | "map"
  | "menu-dots"
  | "pencil"
  | "pepper"
  | "pepper-hot"
  | "play"
  | "refresh"
  | "search"
  | "share"
  | "social-network"
  | "square"
  | "star"
  | "tags"
  | "trash"
  | "triangle-warning";
